#配置dev环境
server:
  port: 7070

spring:
  profiles: dev
  #指定当前微服务暴露的名称
  application:
    name: kkbmsc-consumer-feign-depart

#指定rureka中心
eureka:
  client:
    service-url:
      defaultZone: http://eureka8400.com:8400/eureka
---
#配置test环境
server:
  port: 9090

spring:
  profiles: test
  #指定当前微服务暴露的名称
  application:
    name: kkbmsc-consumer-feign-depart

#指定rureka中心
eureka:
  client:
    service-url:
      defaultZone: http://eureka8500.com:8500/eureka